version: 2.0

jobs:
  Python_3:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: sudo pip install flake8
      - run: flake8 .
workflows:
  version: 2
  build:
    jobs:
      - Python_3
